version: 2
jobs:
  build-svc:
    docker:
      - image: circleci/golang:1.12.7
    working_directory: /cache-service
    steps:
      - checkout
      - run: make lint
      - run: make build
workflows:
  version: 2
  all:
    jobs:
      - build-svc
