version: 2
jobs:
  build-svc:
    docker:
      - image: cimg/go:1.17.5
    steps:
      - checkout
      - run: make test
      - run: make lint
      - run: make build
  make-release-image:
    docker:
      - image: cimg/go:1.17.5
    # TODO : implement make-release-image
    # Maybe this would be
    #  - a github release
    #  - deploy image to a docker repository
    #  - something else
    steps:
      - run: echo "implement make-release-image"

filter_branch_master: &filter_branch_master
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  all:
    jobs:
      - build-svc
      - make-release-image:
          requires:
            - build-svc
          << : *filter_branch_master
