apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service-deployment
  labels:
    app: cache-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
        - image: mdevilliers/cache-service
          name: cache-service
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
              protocol: TCP
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
          # define a readiness probe that checks every 5 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
          env:
            - name: PORT
              value: "3000"
