kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30036 # Binds to well known port for local development of the the cache-service
    hostPort: 30036  # Binds to well known port for local development of the the cache-service
